pose_estimation:
    ros__parameters:
        pattern: "ARUCO"
        image_topic: "/camera/color/image_raw"
        camera_info_topic: "/camera/color/camera_info"
        publish_image_topic: "/image/detected"
        width: 5
        height: 7
        dictionary: "DICT_6X6_250"
        aruco_board_marker_size: 0.035
        aruco_board_marker_seperation: 0.007
