GraspDetectorGPD:
  ros__parameters:
    cloud_topic: /camera/pointcloud
    # cloud_topic: "/camera/aligned_depth_to_color/color/points"
    rviz: true
    device: 0 # 0:CPU, 1:GPU, 2:VPU
    auto_mode: false
    plane_remove: true
    object_detect: false

    # grasp workspace in camera frames
    # workspace: [-0.23, 0.23, -0.33, 0.05, 0.0, 1.0] #original
    workspace: [-0.18, 0.18, -0.25, 0.05, 0.0, 1.0] # lei


    

    # gripper geometry parameters in metre
    # finger_width: the finger thickness
    # hand_outer_diameter: the maximum robot hand aperture 
    # hand_depth: the hand depth (the finger length)
    # hand_height: the finger breadth

    ### costumize
    finger_width: 0.01 #original
    hand_outer_diameter: 0.085 #original 0.12
    hand_depth: 0.05   #original 0.085
    hand_height: 0.01   #original
    
GraspPlanner:
  ros__parameters:

    grasp_service_timeout: 5 #optional(added by LYC)

    grasp_score_threshold: 1
    grasp_frame_id: "base"
    grasp_approach: [0.0, 0.0, -1.0] # expect approaching in -z axis
    # grasp_approach_angle: 0.785 # 1.047=PI/3 # 0.785=PI/4 # 0.523=PI/6 # 0.345=PI/9 0.175=PI/18 # acceptable approaching angle
    grasp_approach_angle: 0.345 # lower angle for safety
    # grasp_offset: [0.000, -0.004, 0.000] #original
    grasp_offset: [-0.01, -0.03, 0.045]


    # grasp boundry in grasp_frame_id
    # grasp_boundry: [-0.25, 0.25, -0.73, -0.27, -0.15, 0.15]
    grasp_boundry: [-1.0, 1.0, -1.0, 1.0, -1.0, 1.0]
    # eef_offset: 0.16 #original-------------
    eef_offset: 0.12  #original 0.12
    # eef_yaw_offset: -0.7854 # M_PI/4 #original----------
    eef_yaw_offset: 0.0 # M_PI/4
    finger_joint_names: ["panda_finger_joint1", "panda_finger_joint2"]

####Axis: red--x; green--y;  blue--z
